//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTime
    {
        public int Id { get; set; }
        public System.DateTime start_Time { get; set; }
        public System.DateTime end_Time { get; set; }
        public int fk_EventId { get; set; }
        public int fk_Location { get; set; }
        public bool IsContinus { get; set; }
        public int Day { get; set; }
<<<<<<< HEAD
    
        public virtual Event Event { get; set; }
        public virtual Location Location { get; set; }
=======
>>>>>>> refs/remotes/origin/master
    }
}
