//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesMetProductid
    {
        public int productId { get; set; }
        public int Price { get; set; }
        public int id { get; set; }
        public string Title { get; set; }
        public string Plot_EN { get; set; }
        public string Plot_NL { get; set; }
        public string Director { get; set; }
        public string Banner { get; set; }
        public string Actors { get; set; }
        public System.DateTime Release { get; set; }
        public int Duration { get; set; }
        public string Trailer { get; set; }
        public string poster { get; set; }
    }
}
