//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public string Title { get; set; }
        public string Infor_NL { get; set; }
        public string Infor_EN { get; set; }
        public string Contact { get; set; }
    }
}
