//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductInOrders = new HashSet<ProductInOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int fk_EventId { get; set; }
<<<<<<< HEAD
        public Nullable<int> Price { get; set; }
        public Nullable<int> Discountable { get; set; }
    
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInOrder> ProductInOrders { get; set; }
=======
        public int Price { get; set; }
        public bool Discountable { get; set; }
>>>>>>> refs/remotes/origin/master
    }
}
