//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInOrder
    {
        public int Id { get; set; }
        public int fk_Product_id { get; set; }
        public int fk_Order_id { get; set; }
        public int Amount { get; set; }
    }
}
