//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Restaurant
    {
        public int Id { get; set; }
        [DisplayName("Naam")]
        public string Name { get; set; }
        [DisplayName("Description")]
        public string Description_EN { get; set; }
        [DisplayName("Beschrijving")]
        public string Description_NL { get; set; }
        [DisplayName("Tijden")]
        public string OpenHours { get; set; }
        public string Poster { get; set; }
        public string Address { get; set; }
        public string SmallimageOne { get; set; }
        public string SmallimageTwo { get; set; }
    }
}
