//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantView
    {
        public int Event_Id { get; set; }
        public bool Special { get; set; }
        public string Name { get; set; }
        public string Description_EN { get; set; }
        public string Description_NL { get; set; }
        public string OpenHours { get; set; }
        public string Poster { get; set; }
    }
}
